Exercices/MVCEF/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEF.Models
{
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public decimal Salary { get; set; }
        public string Designation { get; set; }
    }

}

Exercices/MVCEF/Models/EmployeeDbContext.cs
using Microsoft.EntityFrameworkCore;
using MVCEF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEF.Models
{
    public class EmployeeDbContext : DbContext
    {
        public EmployeeDbContext(DbContextOptions<EmployeeDbContext> options) : base(options)
        {
        }

        public DbSet<Employee> Employees { get; set; }
    }
}

Exercices/MVCEF/ViewModels/EmployeeAddViewModel.cs
using MVCEF.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEF.ViewModels
{
    public class EmployeeAddViewModel
    {
        public List<Employee> EmployeesList { get; set; }

        [Required(ErrorMessage = "Employee Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Employee Designation is required")]
        [MinLength(5, ErrorMessage = "Minimum length of designation should be 5 characters")]
        [RegularExpression(@"^[a-z]+(?:\s[a-z]+)+$", ErrorMessage = "Designation should be at least two words")]
        public string Designation { get; set; }

        [Required]
        [Range(1000, 9999.99)]
        public decimal Salary { get; set; }
    }


}

Exercices/MVCEF/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCEF.ViewModels;
using MVCEF.Models;


namespace MVCEF.Controllers
{
    public class EmployeeController : Controller
    {
        readonly EmployeeDbContext employeeDbContext;
        public EmployeeController(EmployeeDbContext employeeDbContext)
        {
            this.employeeDbContext = employeeDbContext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            EmployeeAddViewModel employeeAddViewModel = new EmployeeAddViewModel();
            var db = this.employeeDbContext;
            employeeAddViewModel.EmployeesList = db.Employees.ToList();

            return View(employeeAddViewModel);
        }
        [HttpPost]
        public IActionResult Index(EmployeeAddViewModel employeeAddViewModel)
        {
            if (ModelState.IsValid)
            {
                    Employee newEmployee = new Employee
                    {
                        Name = employeeAddViewModel.Name,
                        Designation = employeeAddViewModel.Designation,
                        Salary = employeeAddViewModel.Salary
                    };
                    employeeDbContext.Employees.Add(newEmployee);
                    employeeDbContext.SaveChanges();
                    //Redirect to get Index GET method 
                    return RedirectToAction("Index");
            }
            employeeAddViewModel.EmployeesList = employeeDbContext.Employees.ToList();
            return View(employeeAddViewModel);
        }

        [Route("About")]
        public IActionResult About()
        {
            return View();
        }
    }
}

Exercices/MVCEF/Views/Employee/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>
    About...
</h1>

Exercices/MVCEF/Views/Employee/Index.cshtml
@model MVCEF.ViewModels.EmployeeAddViewModel
@*
    //For more information on enabling MVC for empty projects,  visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div>
    <form asp-controller="Employee" asp-action="Index" onsubmit="return validateForm">
        <table>
            <tr>
                <td><label asp-for="Name"></label></td>
                <td><input asp-for="Name" /></td>
                <td>
                    <span asp-validation-for="Name" style="color:red"></span>
                </td>
            </tr>
            <tr>
                <td><label asp-for="Designation"></label> </td>
                <td><input asp-for="Designation" /></td>
                <td>
                    <span asp-validation-for="Designation" style="color:red"></span>
                </td>
            </tr>
            <tr>
                <td><label asp-for="Salary"></label></td>
                <td><input asp-for="Salary"></td>
                <td>
                    <span id="validationSalary" asp-validation-for="Salary"
                          style="color:red"></span>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" id="submitbutton"
                           value="Submit" />
                </td>
            </tr>
        </table>
    </form>
</div>

<br /><br /> <br />

<b> List of employees:</b> <br />
<div>
    <table border="1">
        <tr>
            <th> ID </th>
            <th> Name </th>
            <th> Designation </th>
            <th> Salary </th>
        </tr>
        @foreach (var employee in Model.EmployeesList)
        {
            <tr>
                <td>@employee.EmployeeId</td>
                <td>@employee.Name</td>
                <td>@employee.Designation</td>
                <td>@employee.Salary</td>
            </tr>
        }
    </table>
</div>